title: Cytoso.me
description: For all your placeholder needs
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
# Makes pretty (descriptive) permalinks. See Jekyll docs for alternatives.
permalink: pretty
